### ISSUE TITLE
Incompatible with AdventureBackpacks (and with capes)

### ISSUE THREAD

**Issue by Shadowsnarl** [DarnHyena/CackleheimCode#12]
AdventureBackpack is incompatible. (Additionally, capes can't be equipped.)

Cackleheim shuffles around the equipment a little (if memory serves):
- The trinket to change to gnoll goes into armor slot (and upgrades / equips as a replacement for capes).
- The hat equips into the hat slot (I think?)
- The lower armor (usually pants?) equips to pants (I think?)
- The armor from Cackleheim equips into the cape slot.
- Additionally, the backpack included in Cackleheim equips to the same slot as the belt in the game, which is perfectly valid.

This can be seen if equipping a cape from Valheim's vanilla items, and also the backpacks from AdventureBackpacks (which replace capes and offer similar benefits besides storage).

Among suggestions: The Cackleheim trinket could go to its own unique slot. If there are concerns about armor unbalancing, the trinket could not have armor associated with it.

List of Mods:
- BepInExPack_Valheim
- Blacksmiths_tools
- Jotunn
- Cackleheim_For_Blacksmith
- Craft_Build_Smelt_Cook_Fuel_Pull_From_Containers
- TorchesEternal
- Extra_Snap_Points_Made_Easy
- PlantEasily

**Comment by DarnHyena** [comment]
Yeah, the utility slot felt the most fitting to me to put a backpack. If anything the other backpack centric mods should of probably done it that way too heh. 

A custom slot would be nice but sadly it was the limitations I had to work with at the time due to just being an elaborate suit of armor in the early days of valheim mods.

However there has been a bit of a overhaul quietly in the works that'll help with that issue in the process, but it's not likely to get fixed anytime soon in the mods current form

Thank you for the report nonetheless!
